language: php

php:
  - '8.1'
  - '8.2'
  - '8.3'
  - '8.4'

env:
  - DB=mysql
  - DB=sqlite

before_script:
  - git submodule update --init --recursive
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS pleiades_test; CREATE DATABASE IF NOT EXISTS phpbb_test;'; fi"
  - chmod -R 777 ./app/tmp
  - cp app/Config/database.php.default app/Config/database.php

script:
  - find app -name "*.php" -exec php -l {} +
  - ./app/Console/cake test app AllTests --stderr

notifications:
  email: false